import 'package:flutter/material.dart';
 const Color darkprimaryColor = Color(0xff14A0DD);
 const Color lightPrimaryColor=Color(0xff00B0E7);
 const Color secondaryColor = Color(0xFF3BC2D0);
 const Color backgroundColor = Colors.white;
 const Color textDark = Color(0xFF333333);
 const Color textLight = Color(0xFF666666);
 const Color textGray = Color(0xFF808D9E);
 const Color dividerColor = Color(0xFFE5E5E5);
 const Color errorColor = Color(0xFFE74C3C);